// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCi_PLjyoI_lqJS5bYKaTNdLf3pU-aIJ0',
    appId: '1:345273999578:web:4984af3bbc8a98632205e3',
    messagingSenderId: '345273999578',
    projectId: 'nexus-flutter-fe83a',
    authDomain: 'nexus-flutter-fe83a.firebaseapp.com',
    storageBucket: 'nexus-flutter-fe83a.firebasestorage.app',
    measurementId: 'G-T9WM8RFLGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NjkDg4Hw5ACfTqeMwMeO-r0Sneim58Q',
    appId: '1:345273999578:android:a2a5ebdfbb3d6d2e2205e3',
    messagingSenderId: '345273999578',
    projectId: 'nexus-flutter-fe83a',
    storageBucket: 'nexus-flutter-fe83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClP_qIq3M4GTBZdyX0JWeLebozODo9bjg',
    appId: '1:345273999578:ios:38cff57cdb37cfb22205e3',
    messagingSenderId: '345273999578',
    projectId: 'nexus-flutter-fe83a',
    storageBucket: 'nexus-flutter-fe83a.firebasestorage.app',
    iosClientId: '345273999578-onn1t4p8668bed61lteahajh2n652r58.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClP_qIq3M4GTBZdyX0JWeLebozODo9bjg',
    appId: '1:345273999578:ios:38cff57cdb37cfb22205e3',
    messagingSenderId: '345273999578',
    projectId: 'nexus-flutter-fe83a',
    storageBucket: 'nexus-flutter-fe83a.firebasestorage.app',
    iosClientId: '345273999578-onn1t4p8668bed61lteahajh2n652r58.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCi_PLjyoI_lqJS5bYKaTNdLf3pU-aIJ0',
    appId: '1:345273999578:web:e42f61c7875e3cfe2205e3',
    messagingSenderId: '345273999578',
    projectId: 'nexus-flutter-fe83a',
    authDomain: 'nexus-flutter-fe83a.firebaseapp.com',
    storageBucket: 'nexus-flutter-fe83a.firebasestorage.app',
    measurementId: 'G-6Q5VCDGCHJ',
  );
}
